### ISSUE TITLE
Wrong URL in repository description

### ISSUE THREAD

**Issue by gkalpak** [Microsoft/vscode-wiki#1]
The repository's description points to the TypeScript wiki, instead of the one for VSCode:

> A repository to make changes to the vscode Wiki on GitHub https://github.com/Microsoft/TypeScript/wiki

It should be changed to:
> A repository to make changes to the vscode Wiki on GitHub: https://github.com/Microsoft/vscode/wiki

**Comment by Tyriar** [comment]
Thanks for spotting this @gkalpak, fixed 😃
