### ISSUE TITLE
How does this become vscode's wiki?

### ISSUE THREAD

**Issue by nhooyr** [Microsoft/vscode-wiki#112]
Is it mirrored to Microsoft/vscode.wiki whenever it is updated?

AFAIK, github doesn't have a native option to make the wiki its own github repository.

**Comment by Tyriar** [comment]
@nhooyr I wrote about how we're doing it [on my personal blog](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html), we're using Azure Pipelines behind the scenes for the sync job.

**Comment by nhooyr** [comment]
Thank you.
