### ISSUE TITLE
Git-wiki as alternative

### ISSUE THREAD

**Issue by Yehonal** [Microsoft/vscode-wiki#113]
Can i suggest you to use git-wiki as alternative? it allows you to directly edit the wiki and supports pull requests for external contributors. Moreover has tons of features that a wiki should have while github wiki lacks:

https://github.com/Drassil/git-wiki

The list of all wikis made with git-wiki: 
http://www.drassil.org/git-wiki/examples.html

**Comment by Tyriar** [comment]
We're not planning on changing, the current system is integrated into github via https://github.com/Microsoft/vscode/wiki and supports pull requests.
