### ISSUE TITLE
Animated timer tied code

### ISSUE THREAD

**Issue by GeorgeAAbraham** [Microsoft/vscode-wiki#16]
Would be kinda cool to see, in a static coding console. All the components tied to timed opperations like the Angular2 ng* stuff, to animate like strobing colour text.

And have intellisense animate all the methods or bound opperations animate as well to remind you of the paradigm.

**Comment by roblourens** [comment]
I don't totally understand the request but I don't think it's related to the wiki. Please file in the vscode repo if it's a feature request for vscode.
