### ISSUE TITLE
Filename 'Test:-Smoke-Test-Template.md' prevents checkout onto Windows

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-wiki#161]
When I forked this repo and tried to clone it from within VS Code Insiders it failed. Here is the relevant information from the log:

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.29.2.windows.2 from C:\Program Files\Git\cmd\git.exe
> git clone https://github.com/gjsjohnmurray/vscode-wiki.git c:\Users\XXX\Documents\YYY\gjsjohnmurray\vscode-wiki --progress
Cloning into 'c:\Users\XXX\Documents\YYY\gjsjohnmurray\vscode-wiki'...
remote: Enumerating objects: 59, done.
...
error: invalid path 'Test:-Smoke-Test-Template.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Please rename that file so as not to use the colon character.

**Comment by Tyriar** [comment]
🤦 

I renamed the page to use a hyphen instead https://github.com/microsoft/vscode/wiki/Test---Smoke-Test-Template, that should rename the folder when the repo gets synced, ping me if it didn't end up renaming the file by Monday.

**Comment by gjsjohnmurray** [comment]
@Tyriar I'm not yet seeing the rename at https://github.com/microsoft/vscode-wiki

**Comment by Tyriar** [comment]
Looking into it, the sync job's been broken for quite a while 🙁

**Comment by Tyriar** [comment]
Fixed, thanks for letting me know
