### ISSUE TITLE
`How to Contribute` has confusing build instructions

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode-wiki#166]
Under the [Build](https://github.com/microsoft/vscode-wiki/blob/1f0f25b/How-to-Contribute.md#build) section there are seemingly VS Code commands in place of where command line commands would be. It appears as though this was introduced in https://github.com/microsoft/vscode-wiki/commit/659f67e when `yarn watch` was removed and replaced by a VS Code command.

The previous iteration (https://github.com/microsoft/vscode-wiki/blob/2e2d6b0/How-to-Contribute.md#build) is much clearer and the VS Code build option is secondary to the command line option (it also might be a little unintuitive to use VS Code to make a development build of VS Code).

**Comment by joaomoreno** [comment]
Improved: https://github.com/microsoft/vscode/wiki/How-to-Contribute#build
