### ISSUE TITLE
Inaccurate representation of legend in Roadmap

### ISSUE THREAD

**Issue by aravindvnair99** [microsoft/vscode-wiki#180]
Being a legend, it doesn't accurately represent the respective icons:

![image](https://user-images.githubusercontent.com/22199259/112508765-da89e800-8db5-11eb-9cbf-8305c8e5ef95.png)

A better representation would be to show the actual icon as opposed to having text.

**Comment by Tyriar** [comment]
We'll be updating the roadmap any day now so let's leave this as is for now.
