### ISSUE TITLE
wiki/How-to-Contribute#translations Localization Site link gives Octobi Wan Catnobi (404)

### ISSUE THREAD

**Issue by devashish-gaikwad** [microsoft/vscode-wiki#183]
- VS Code Version: Not applicable
- OS Version: Not applicable
- Browser Version: Google Chrome Version 70.0.3538.67 (Official Build) (64-bit)

Steps to Reproduce:

1. Go to https://github.com/microsoft/vscode/wiki/How-to-Contribute#translations in browser
2. Click on [localization site](https://github.com/Microsoft/Localization/wiki)

Summary:
https://github.com/Microsoft/Localization/wiki is not reachable 

I am new to OSS contributing and would like to fix this issue!
Could you please assign this to me and If possible could you please give the correct Link here so that I can fix it and set a pull request ? :)

**Comment by dbaeumer** [comment]
@nexue2020 can you please advise to which site we should link especially considering the new translation process. How do you envision that the community will participate in translations in the future.

**Comment by dbaeumer** [comment]
I for now point the people to open issues in VS Code repository.

**Comment by Tyriar** [comment]
Ping @dbaeumer @TylerLeonhardt @nexue2020

I like to keep this repo's open issue count at 0

**Comment by TylerLeonhardt** [comment]
I pinged @nexue2020 on Teams so we should get this figured out soon.

**Comment by nexue2020** [comment]
@dbaeumer  That's correct. I had a sync-up with the team earlier this morning. Opening issues in VS Code repository would be the current method. There expect to be further announcement around open-source community contribution to localization later this month. Stay tuned.

**Comment by dbaeumer** [comment]
OK. Then lets close the issue since this is what I have done.
