### ISSUE TITLE
Possible typo in Virtual-Workspaces page (linked to from 1.56 release notes)

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-wiki#184]
At the end of https://github.com/microsoft/vscode/wiki/Virtual-Workspaces#disable-functionality-when-a-virtual-workspace-is-opened it says:

A second way is to check in code whether the current workspace consists of non-file schemes:
```
const isVirtualWorkspace = workspace.workspaceFolders && workspace.workspaceFolders.every(f => f.uri.scheme === 'file');
```

I think `===` should be `!==`

I can't submit a PR because the page source doesn't yet appear in this repo.

Pinging @aeschli

**Comment by aeschli** [comment]
Thanks a lot. 
Note, this document is still work in progress.
