### ISSUE TITLE
How-To-Contribute > Packaging is outdated

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode-wiki#185]
https://github.com/microsoft/vscode/wiki/How-to-Contribute#packaging

`darwin` isn't a valid option anymore.  I am not sure all the options, but I needed to run `vscode-darwin-x64-min` to build.

**Comment by Tyriar** [comment]
Fixed: https://github.com/microsoft/vscode/wiki/How-to-Contribute/4c7f376c488bc3ff6e4277e577f0d79be88e66fa
