### ISSUE TITLE
2021 roadmap

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [microsoft/vscode-wiki#188]
Is there a roadmap for 2021 somewhere?

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/wiki/Roadmap

**Comment by Bosch-Eli-Black** [comment]
Thanks 🙂  Should https://github.com/microsoft/vscode-wiki/blob/main/Roadmap.md link to there? Sorry, I'm new to the VSCode Github repositories 😅

**Comment by Tyriar** [comment]
Thanks for pointing this out, the sync job was broken but I fixed it and resynced so everything should be up to date now.

**Comment by Bosch-Eli-Black** [comment]
Thanks! 🙂
