### ISSUE TITLE
Source-Code-Organization.md what is the "code" layer?

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode-wiki#197]
Hi maintainers, the [Source-Code-Organization.md "Layers"](https://github.com/microsoft/vscode-wiki/blob/main/Source-Code-Organization.md#layers) covers several directories under `src/vs/`: `base`, `platform`, `editor`, `workbench`, but not `code`. Could you add it there, or explain why `code` is not a layer itself?

**Comment by Tyriar** [comment]
Added 👍 https://github.com/microsoft/vscode/wiki/Source-Code-Organization
