### ISSUE TITLE
`How-to-contribute` recommends deprecated module "Windows-build-tools"

### ISSUE THREAD

**Issue by stampyzfanz** [microsoft/vscode-wiki#208]
The [github page for Windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) states
> Please note that the official [Node.js for Windows installer](https://nodejs.org/en/download/) can now automatically install the required tools. That's likely a much better option than the module listed here (`windows-build-tools`).

Its [npm page](https://www.npmjs.com/package/windows-build-tools) states
> This package has been deprecated
> Node.js now includes build tools for Windows. You probably no longer need this tool. See https://github.com/felixrieseberg/windows-build-tools for details.

**Comment by joaomoreno** [comment]
This is fine for now. If we end up changing something which stops working in this setup, we'll figure out new steps.
