### ISSUE TITLE
A weird word in the "Automated Issue Triaging" page

### ISSUE THREAD

**Issue by ismailarilik** [microsoft/vscode-wiki#241]
https://github.com/microsoft/vscode/wiki/Automated-Issue-Triaging#training

In this page I see this statement: `This is manually verified on a test issue stream, then deployed to vscode proper by copying some bata around in Azure Blob Storage.` And I suspect that the word `bata` is wrong here. It may be `data` but I am not sure so I am opening an issue instead of a PR.

**Comment by Tyriar** [comment]
Pretty sure it was data, fixed in https://github.com/microsoft/vscode/wiki/Automated-Issue-Triaging/9c983a9f42640a693bd8ff953a180c5a6dc7fb06

Thanks!
