### ISSUE TITLE
Wiki should include a little more information on how vscode is working from scratch.

### ISSUE THREAD

**Issue by modeware** [microsoft/vscode-wiki#247]
I was looking to contribute to VSCODE with good first issues as a newbie/beginner. The [source code organisation](https://github.com/microsoft/vscode/wiki/Source-Code-Organization) section does a pretty good job at explaining the folder structures to someone who **has a lot of experience**. 

**But for the rest of us it is not helpful at all. First of all the information should be very beginner friendly, if some one new is looking to get into open source development.**

If anyone of you, who has a lot of experience in contributing to VSCODE, whether  in Microsoft or outside kindly add some beginner friendly information. It will be a great help for the community.

**For a start here are some of my question that are not available anywhere properly/not at all.**

![image](https://user-images.githubusercontent.com/25425426/203239574-7ca1e11f-dfc1-4c3f-9928-190211cfdfaf.png)

1. For example take the status bar - I as a beginner developer would like add a text say "Hello World" on to the status bar. Which part  of the codebase is responsible for creating the status bar? How is it at the end rendering to the screen? How does everything stick together? 

What are some of the key apis within VSCODE that can be leveraged?

2. How are different sections of the VSCODE - statusbar, sidebar, editor, header, etc being combined? 
For example in react - we have an App.ts file where ultimately everything goes together and the code style is very declarative.
The VSCODE code base is based on what? How do I even connect the dots?

![image](https://user-images.githubusercontent.com/25425426/203240526-4cac5ed0-df13-4e65-b1e4-e61321565b77.png)
And then what is this Resgitry.registerViewContainer actually doing? 

There are a bunch of classes, huge files with events, everything abstracted out. So if that is the case. We need a doc where beginners can understand why the architecture is the way it is, how things connect, how can they make changes by understanding the actual inner workings of VSCODE and not just randomly stumble upon the code trying to guess what exactly is happening.

cc: @jrieken

**Comment by Tyriar** [comment]
It's actually intentional we don't go so deep in the core codebase because it would hinder our ability to change and the docs would get stale quickly. It sounds like maybe you're after an extension instead if you want to add a status bar entry which has much more details documentation https://code.visualstudio.com/api/get-started/your-first-extension

If you did want to contribute something to core, I'd recommend just browsing the codebase via searches and experimenting.

**Comment by modeware** [comment]
Okay, you mean the architecture has been prepared such that the changes are to be made via extensions. But I want to understand how everything connects.

A react application for example sets - innerHTML of a root div with the application contents in a declarative way.

In the VSCODE's codebase all I see are register methods and could not connect it back to how a typical web app renders elements. Is there a specific design pattern you are using?

Also, this the right place to ask such questions? Slack and other places don't seem to be so much welcoming and these questions get ignored.

**Comment by Tyriar** [comment]
We don't use a framework and things are a little different depending on where you are in the codebase. You can search for `createElement` or `layout` for examples on how things are rendered to the DOM
