### ISSUE TITLE
Consider building with windows-build-tools npm package

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode-wiki#26]
Hello

For building on Windows, it recommends using:

```
Visual Studio 2013 for Windows Desktop or Visual Studio 2015, make sure to select the option to install all C++ tools and the Windows SDK
```

I had VS2017 installed but it wasn't recognized. Rather then install 2015 or mess around with paths, I discovered an npm package that includes the tools.

`npm install --global windows-build-tools`

Works great, no further configuration needed. Might be useful to add to the readme.

**Comment by wkamir** [comment]
I second that - I recently did a clean install on my dev machine and of course only wanted to have Visual Studio 2017 installed. After a bit of googling (for "node-gyp prerequisites") I found that all you have to do is

`
npm install --global --production windows-build-tools
`

Got the information from here: 
[node-gyp](https://github.com/nodejs/node-gyp)

Works great, no need to install 14GB of Visual Studio 2015
