### ISSUE TITLE
Dev contaienrs doens't help when using Windows

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode-wiki#260]
Hi

So, I was trying to make vscode work in Windows with Dev Containers because this was how it was instructed to do... But I was facing some issues, [learn more here](https://stackoverflow.com/questions/76098631/trying-to-build-and-run-vscode-for-contribution-but-the-code-bat-script-doesnt).

The solution what to not use Dev Containers and anything like that.

Should I open a PR and update the docs with something like "you may don't like to use Dev Containers"? Something like that...

**Comment by Tyriar** [comment]
Dev containers create a Linux sub-system using a Dockerfile, if you're trying to work on a Windows client it doesn't make sense to use a dev container afaik. Let's leave this out of the docs for now to avoid cluttering them and making them more complicated than they need to be

**Comment by babakfp** [comment]
How does adding missing documentation make the documentation more complicated? That doesn't make sense.
If it was documented, I wasn't going to waste 1 or 2 days of my life trying to get it to work. But sure, let's don't make the docs more complicated. Let's also blame the developer that tries to contribute 👍.

**Comment by Tyriar** [comment]
It makes it more complicated because it would make the already extremely large page larger https://github.com/microsoft/vscode/wiki/How-to-Contribute, every line on that document raises the bar for contributions. I don't blame you and no offence was intended.
