### ISSUE TITLE
Travis and Appveyor in How to Contribute

### ISSUE THREAD

**Issue by mchels** [Microsoft/vscode-wiki#32]
Can you put links to Travis and Appveyor on the How to Contribute page and explain that they contain information about the versions needed to build vscode? I spent a lot of time this week searching through build issues for this information until I realized that it's abundantly available in Travis and Appveyor.

**Comment by Tyriar** [comment]
What versions were you unsure about?

**Comment by mchels** [comment]
After reading How to Contribute I wasn't unsure about any version in particular. Having tried to compile on various combinations of (Windows 10, Windows Subsystem for Linux) x (nodejs 7, nodejs 8) x (npm 3.10.8, npm 4.x) I assumed that some versions had to be wrong (or that I messed up somewhere). What finally made it work was your comment
https://github.com/Microsoft/vscode/issues/32941#issuecomment-324469496
about using npm 3.10.10 (thanks, by the way). Since npm 3.10.8 didn't work and npm 4.x didn't work I wouldn't have thought of trying npm 3.10.10 since How to Contribute says "be sure to install npm >= 3.10.8", except for your comment.

I didn't know what Travis and Appveyor was before I accidentally clicked on the links in my it-finally-compiled frenzy, but if there had been a mention in How to Contribute I would have gotten it to work much faster. Even something short in parentheses along the lines of
"(If the build doesn't seem to work, consider looking at our internal build log available here)"
would have helped me immensely.

**Comment by Tyriar** [comment]
I updated the wiki to include new recommended versions of node/npm. FYI @joaomoreno https://github.com/Microsoft/vscode/wiki/How-to-Contribute/_compare/af745ca3a0b01fe6e67d40a7c6578ed0bfac3421...090e5436efaaad97ae4483cd8b131bf6197bce98
