### ISSUE TITLE
Use canonical GitHub URLs that don't move

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-wiki#33]
At the bottom of the [multi root wiki page](https://github.com/Microsoft/vscode-wiki/blob/4227d1c2a5908887813f95a1e28f0c902f2ae4ba/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs.md), there is a link to vscode-tslint.

```MarkDown
An example for this can be found in [vscode-tslint](https://github.com/Microsoft/vscode-tslint/blob/master/tslint/extension.ts#L200)
```

The link points to a line number on the `master` branch. This is bad because `master` will change (or maybe it has already changed since this edit) and line 200 will then be pointing at the wrong thing.

Please use <kbd>y</kbd> to get and link to [permalinks](https://help.github.com/articles/getting-permanent-links-to-files/) instead.

**Comment by egamma** [comment]
@rcjsuen good catch - fixed. Thanks.
