### ISSUE TITLE
Wrong URL in vscodes-themes

### ISSUE THREAD

**Issue by leocabeza** [Microsoft/vscode-wiki#5]
The URL in this link:

[https://github.com/Microsoft/vscode/wiki/Related-Projects#themes](https://github.com/Microsoft/vscode/wiki/Related-Projects#themes)

which is this: https://github.com/microsoft/vscode-themes gives a 404 - Page not found.

**Comment by Tyriar** [comment]
We just made the repository public so the link works now! Thanks for the report :smiley:
