### ISSUE TITLE
Update step for installing Visual Studio in How to Contribute

### ISSUE THREAD

**Issue by NRKirby** [Microsoft/vscode-wiki#51]
In the [Prerequisites](https://github.com/Microsoft/vscode-wiki/blob/master/How-to-Contribute.md#prerequisites) (Windows) section of How to Contribute, the step for installing Visual Studio appears to be out of date:

> - [Visual Studio 2013 for Windows Desktop](https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx?wt.mc_id=github_microsoft_vscode) or [Visual Studio 2015](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx?wt.mc_id=github_microsoft_vscode), make sure to select the option to install all C++ tools and the Windows SDK.

When I was following this guide yesterday, I installed Visual Studio 2017 and was able to build and run the source seemingly without any problems.

Should this guide be updated for 2017 and link to the [Visual Studio](https://www.visualstudio.com/downloads/) download page?

If you could let me know how and if this step should be changed, I will happily submit a PR

**Comment by joaomoreno** [comment]
Done: https://github.com/Microsoft/vscode/wiki/How-to-Contribute
