### ISSUE TITLE
Etiquette: Contributors should mention in the issue if they are working on a fix.

### ISSUE THREAD

**Issue by ozyx** [Microsoft/vscode-wiki#58]
Hi,

This is a request to include somewhere in the Contributing guide the etiquette of letting others know when you are working on an issue. Recently, I ran into a problem where I had spent hours preparing a fix for an issue and had informed others in the comment thread that I had a commit which was being prepared, only to be "beaten to the punch" by another user who opened a PR for the same issue.

This is frustrating because if I had known that this other user was working on the issue, I would have chosen another open issue instead of wasting time working in parallel of someone else on the same thing. I think it would be helpful to include this note in the "etiquette" section of the contributing guide, just so that contributors can have better communication among each other to avoid situations like this in the future. After all, time is in short supply so we should all be able to work together to make the most of the time we have.

Thanks for your consideration,
Jesse

**Comment by Tyriar** [comment]
This is kind of already mentioned in https://github.com/Microsoft/vscode/wiki/How-to-Contribute#where-to-contribute

> To improve the chances to get a pull request merged you should select an issue that is labelled with the help-wanted or bug labels. If the issue you want to work on is not labelled with help-wanted or bug, you can start a conversation with the issue owner asking whether an external contribution will be considered.

We could make it a little more explicit though.

**Comment by ozyx** [comment]
Just to clarify, I am requesting that potential contributors (outside of Microsoft-- therefore unable to be "assigned" issues) make it clear in the issue's comment thread that they are currently working on a fix so that others do not start work on the same issue (Just a brief comment such as "I'm working on a fix for this"). Since we are outside of the organization, communication is really the only tool we have in order to avoid "PR races". 

I think it's reasonable to briefly mention this as part of good contributor etiquette.

**Comment by Tyriar** [comment]
Yep I agree, that paragraph can be amended to be explicit about collisions with other contributors since CONTRIBUTING.md points to that wiki page.

**Comment by juliegoat** [comment]
In the spirit of this issue:

I'm an outside contributor and I'd love to add this for you :)
