### ISSUE TITLE
Linux FAQ page link in How To Contribute does not have ENOSPC information specified 

### ISSUE THREAD

**Issue by ianrobrien** [Microsoft/vscode-wiki#6]
The link below does not point to any information about ENOSPC error:

> **Tip!** Linux users may hit a ENOSPC error when running `npm run watch`, to get around this follow instructions in the [Linux FAQ](https://code.visualstudio.com/docs/supporting/faq#_linux-faq).

I propose changing this link to point to: `[Common Questions](https://code.visualstudio.com/docs/setup/linux#_common-questions).`

**Comment by ianrobrien** [comment]
I came across this issue while trying to set up my environment to build Code. The wiki page pointed to the wrong place so I thought I would update this with the solution/page I found.

**Comment by Tyriar** [comment]
Fixed via https://github.com/Microsoft/vscode-wiki/pull/7
