### ISSUE TITLE
Guide `How to Contribute` is a bit outdated

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode-wiki#9]
> You can identify the development version of Code by the **Electron icon** in the Dock or Taskbar.
> 
> https://github.com/Microsoft/vscode/wiki/How-to-Contribute#validate-your-changes

Current icon:

![image](https://cloud.githubusercontent.com/assets/7034281/17980235/e65ce050-6b06-11e6-885b-6a3fa0c70d5d.png)

**Comment by Tyriar** [comment]
I think OS X still shows an electron icon and Linux and Windows show the Code OSS icon.

**Comment by mrmlnc** [comment]
@Tyriar, maybe just write, that icon will be different from the original VS Code icon?

In any case, I just pointed out the inaccuracy :panda_face:

**Comment by Tyriar** [comment]
@mrmlnc yep thanks, just adding some more info for whoever fixes it :smiley:

**Comment by mrmlnc** [comment]
I think is outdated issue.
